unit KeyCodes;

interface
const
     F1=15104;
     F2=15360;
     F3=15616;
     F4=15872;
     F5=16128;
     F6=16384;
     F7=16640;
     F8=16896;
     F9=17152;
     F10=17408;

     Enter=13;
     Esc=27;
     Space=32;
     Tab=9;
     BackSpace=8;

     UpKey=18432;
     DownKey=20480;
     LeftKey=19200;
     RightKey=19712;

     InsertKey=20992;
     DeleteKey=21248;
     HomeKey=18176;
     EndKey=20224;
     PageUp=18688;
     PageDown=20736;

     CtrlR=18;

     AltM=12800;

     AltF1=26624;
     AltF2=26880;

implementation


end.